```{r}
#| label: evaluefunc
#| cache: true
#| cache.comments: false
#| dependson: tbl-outcomes

evalfunc <- function(eventname, rep = FALSE) {
  oute <- data.frame(matrix(NA, ncol = 5, nrow = 1))
  colnames(oute) <- c("Outcome", rep(c("E-value (Lower CI-)"), 4))

  oute[, 1] <- eventname

  ests <- outall %>%
    filter(Outcome == eventname & str_detect(Model, "Adjusted"))

  if (!rep) {
    oute[2] <- paste0(paste0(fn(
      evalue(HR(ests$hr1.x, rare = FALSE),
        lo = ests$lci1.x,
        hi = ests$uci1.x,
      )["E-values", 1:2],
      dig = 2
    ), collapse = " ("), "-)")
    oute[3] <- paste0(paste0(fn(
      evalue(HR(ests$hr2.x, rare = FALSE),
        lo = ests$lci2.x,
        hi = ests$uci2.x,
      )["E-values", 1:2],
      dig = 2
    ), collapse = " ("), "-)")
    oute[4] <- paste0(paste0(fn(
      evalue(HR(ests$hr1.y, rare = FALSE),
        lo = ests$lci1.y,
        hi = ests$uci1.y,
      )["E-values", 1:2],
      dig = 2
    ), collapse = " ("), "-)")
    oute[5] <- paste0(paste0(fn(
      evalue(HR(ests$hr2.y, rare = FALSE),
        lo = ests$lci2.y,
        hi = ests$uci2.y,
      )["E-values", 1:2],
      dig = 2
    ), collapse = " ("), "-)")
  }

  if (rep) {
    oute[2] <- paste0(paste0(fn(
      evalue(RR(ests$hr1.x),
        lo = ests$lci1.x,
        hi = ests$uci1.x,
      )["E-values", 1:2],
      dig = 2
    ), collapse = " ("), "-)")
    oute[3] <- paste0(paste0(fn(
      evalue(RR(ests$hr2.x),
        lo = ests$lci2.x,
        hi = ests$uci2.x,
      )["E-values", 1:2],
      dig = 2
    ), collapse = " ("), "-)")
    oute[4] <- paste0(paste0(fn(
      evalue(RR(ests$hr1.y),
        lo = ests$lci1.y,
        hi = ests$uci1.y,
      )["E-values", 1:2],
      dig = 2
    ), collapse = " ("), "-)")
    oute[5] <- paste0(paste0(fn(
      evalue(RR(ests$hr2.y),
        lo = ests$lci2.y,
        hi = ests$uci2.y,
      )["E-values", 1:2],
      dig = 2
    ), collapse = " ("), "-)")
  }
  return(oute)
}

death <- evalfunc(
  eventname = "All-cause mortality"
)
cvdeath <- evalfunc(
  eventname = "CVD"
)
hfhosp <- evalfunc(
  eventname = "First HFH"
)
rephfhosp <- evalfunc(
  eventname = "Total HFH",
  rep = TRUE
)
cvdeathhfhosp <- evalfunc(
  eventname = "First HFH/CVD"
)
cvdeathrephfhosp <- evalfunc(
  eventname = "Total HFH/CVD",
  rep = TRUE
)

evalout <- rbind(
  cvdeathhfhosp,
  cvdeath,
  hfhosp,
  rephfhosp,
  cvdeathrephfhosp,
  death
)
```

```{r}
#| label: tbl-evalue
#| cache: true
#| cache.comments: false
#| dependson: evaluefunc
#| tbl-cap: "Residual confounding - E-value"
#| tbl-pos: "H"

make_one_xlsxsheet(evalout)

default_kable(evalout,
  escape = FALSE
) %>%
  add_header_above(c(" ", "Dose 1-40mg" = 1, "Dose >40mg" = 1, "Dose 1-40mg" = 1, "Dose >40mg" = 1)) %>%
  add_header_above(c(" ", "Population 1" = 2, "Population 2" = 2))
```
