```{r}
#| label: kmfunc
#| cache: true
#| cache.comments: false
kmfunc <- function(time, event, eventname, xvar = "shf_loopdiuretic_cat", data, endfollow = global_followup / 365.25, labposadj = c(-0.06, -0.06, 0.12)) {
  levs <- levels(data %>% pull(!!sym(xvar)))
  nlevs <- length(levs)

  # cox results
  mod <- summary(coxph(formula(paste0("Surv(", time, ",", event, "== 'Yes') ~ ", xvar)),
    data = data
  ))
  cox <- paste0(c(
    "Crude HR (95% CI)",
    "ref",
    paste0(
      fn(mod$conf.int[, "exp(coef)"], dig = 2),
      " (", fn(mod$conf.int[, "lower .95"], dig = 2),
      "-", fn(mod$conf.int[, "upper .95"], dig = 2), ")"
    )
  ), collapse = "\n")

  fit <- survfit(formula(paste0("Surv(", time, ",", event, "== 'Yes') ~ ", xvar)),
    data = data
  )

  s <- summary(fit, times = seq(0, 365 * endfollow, 1), extend = T)

  plot_data <- tibble(
    "time" = s$time,
    "n.risk" = s$n.risk,
    "n.event" = s$n.event,
    "n.censor" = s$n.censor,
    "estimate" = s$surv,
    "std.error" = s$std.err,
    "strata" = s$strata
  ) %>%
    mutate(strata = fct_rev(fct_inorder(str_remove_all(strata, paste0(xvar, "=")))))

  annotate_data <- plot_data %>%
    filter(time == 2 * 365)

  p <- ggplot(plot_data, aes(x = time / 365.25, y = 1 - estimate, color = strata)) +
    geom_step(aes(linetype = strata), linewidth = 1) +
    scale_color_brewer(palette = "Set1") +
    # scale_x_continuous(breaks = seq(0, endfollow, 1), limits = c(0, endfollow), expand = c(0, 0)) +
    # scale_y_continuous(labels = scales::label_percent(suffix = ""), limits = c(0, 1), expand = c(0, 0)) +
    scale_x_continuous(breaks = seq(0, endfollow, 1), limits = c(0, endfollow)) +
    scale_y_continuous(labels = scales::label_percent(suffix = ""), limits = c(0, 1)) +
    theme_classic() +
    theme(
      text = element_text(size = 20),
      legend.position = "none"
    ) +
    labs(x = "Follow-up (years)", y = paste0(eventname, " (%)")) +
    ggrepel::geom_text_repel(
      data = annotate_data,
      aes(x = time / 365.25, y = (1 - estimate), label = strata),
      nudge_x = 0, nudge_y = labposadj, size = 6, hjust = 0
    ) +
    annotate("text", x = 0, y = .85, label = paste0(c("", levs), collapse = "\n"), hjust = 0, size = 6) +
    annotate("text", x = 1.65, y = .85, label = cox, hjust = 0.5, size = 6)

  # n at risk
  table_data <- plot_data %>%
    filter(
      time %in% c(seq(0, endfollow, 1) * 365)
    )

  t <- ggplot(table_data, aes(y = strata, x = time / 365)) +
    geom_text(aes(label = n.risk), size = 6) +
    # scale_x_continuous(breaks = seq(0, endfollow, 1), limits = c(0, endfollow), expand = c(0, 0)) +
    # scale_y_discrete(expand = c(0, 0)) +
    scale_x_continuous(breaks = seq(0, endfollow, 1), limits = c(0, endfollow)) +
    coord_cartesian(xlim = c(0, endfollow), clip = "off") +
    labs(subtitle = "No. at risk") +
    theme(
      plot.caption = element_text(size = 20),
      panel.background = element_blank(),
      text = element_text(size = 20),
      axis.text.x = element_blank(),
      axis.ticks = element_blank(),
      axis.title = element_blank(),
      # plot.margin = unit(c(0, 1, 0, 3), "cm"), # trouble
      # axis.text.y = element_blank()
      # axis.text.y = element_text(margin = margin(0, 0, 0, 100))
      axis.text.y = element_text(hjust = 0, colour = "black")
    )

  km <- (p / t) + plot_layout(height = c(1, .25))
  km
}

mcffunc <- function(event, eventno, eventname, xvar = "shf_loopdiuretic_cat", data, datarec,
                    endfollow = global_followup / 365.25, labposadj = c(-0.1, -0.1, -0.1)) {
  levs <- levels(data %>% pull(!!sym(xvar)))
  nlevs <- length(levs)

  # neg bin results
  mod <- summary(glm.nb(formula(paste0(eventno, " ~ ", xvar, " + offset(log(sos_outtime_death))")),
    data = data %>% filter(sos_outtime_death > 0)
  ))

  cox <- paste0(c(
    "Crude RR (95% CI)",
    "ref",
    paste0(
      fn(exp(mod$coefficients[2:nlevs, 1]), dig = 2),
      " (", fn(exp(mod$coefficients[2:nlevs, 1] - global_z05 * mod$coefficients[2:nlevs, 2]), dig = 2),
      "-", fn(exp(mod$coefficients[2:nlevs, 1] + global_z05 * mod$coefficients[2:nlevs, 2]), dig = 2), ")"
    )
  ), collapse = "\n")

  fit <- mcf(formula(paste0("Recur(sos_outtime, lopnr, ", event, " == 1) ~ ", xvar)), data = datarec)

  plot_data <- tibble(
    "time" = fit@MCF$time,
    "n.risk" = fit@MCF$numRisk,
    "estimate" = fit@MCF$MCF,
    "std.error" = fit@MCF$se,
    "strata" = fit@MCF[[xvar]]
  ) %>%
    mutate(strata = fct_rev(strata))

  annotate_data <- plot_data %>%
    filter(time <= 2 * 365) %>%
    group_by(strata) %>%
    slice(n()) %>%
    ungroup()

  p <- ggplot(plot_data, aes(x = time / 365.25, y = estimate, color = strata)) +
    geom_step(aes(linetype = strata), linewidth = 1) +
    scale_color_brewer(palette = "Set1") +
    scale_x_continuous(breaks = seq(0, endfollow, 1), limits = c(0, endfollow)) +
    scale_y_continuous(labels = scales::label_percent(suffix = ""), limits = c(0, 2.5)) +
    theme_classic() +
    theme(
      text = element_text(size = 20),
      legend.position = "none"
    ) +
    labs(x = "Follow-up (years)", y = paste0("Cumulative mean of ", eventname, "\n(/100 patients)")) +
    ggrepel::geom_text_repel(
      data = annotate_data,
      aes(x = time / 365.25, y = estimate, label = strata),
      nudge_x = 0, nudge_y = labposadj, size = 6, hjust = 0
    ) +
    annotate("text", x = 0, y = 2.1, label = paste0(c("", levs), collapse = "\n"), hjust = 0, size = 6) +
    annotate("text", x = 1.65, y = 2.1, label = cox, hjust = 0.5, size = 6)

  # n at risk
  # needed for n at risk
  fitn <- survfit(formula(paste0("Surv(sos_outtime_death, sos_out_death == 'Yes') ~ ", xvar)),
    data = data
  )
  sn <- summary(fitn, times = seq(0, 365 * endfollow, 1), extend = T)

  table_data <- tibble(
    "time" = sn$time,
    "n.risk" = sn$n.risk,
    "strata" = sn$strata
  ) %>%
    filter(
      time %in% c(seq(0, endfollow, 1) * 365)
    ) %>%
    mutate(strata = str_remove_all(strata, paste0(xvar, "=")))

  t <- ggplot(table_data, aes(y = strata, x = time / 365)) +
    geom_text(aes(label = n.risk), size = 6) +
    scale_x_continuous(breaks = seq(0, endfollow, 1), limits = c(0, endfollow)) +
    coord_cartesian(xlim = c(0, endfollow), clip = "off") +
    labs(subtitle = "No. at risk") +
    theme(
      plot.caption = element_text(size = 20),
      panel.background = element_blank(),
      text = element_text(size = 20),
      axis.text.x = element_blank(),
      axis.ticks = element_blank(),
      axis.title = element_blank(),
      axis.text.y = element_text(hjust = 0, colour = "black")
    )

  km <- (p / t) + plot_layout(height = c(1, .25))
  km
}
```

```{r}
#| label: fig-cicmcf-pop-1
#| cache: true
#| cache.comments: false
#| dependson: kmfunc
#| fig-cap: "Cumulative incidence curve/Mean cumulative function - Population 1"
#| fig-subcap:
#|   - "HFH/CVD"
#|   - "CVD"
#|   - "HFH"
#|   - "Total HFH"
#|   - "Total HFH/CVD"
#|   - "All-cause mortality"
#| layout-ncol: 2
#| layout-nrow: 3

kmfunc(
  time = "sos_outtime_hosphf",
  event = "sos_out_deathcvhosphf",
  eventname = "HFH/CVD",
  data = rsdata %>% filter(pop1),
  labposadj = c(-0.06, -0.06, -0.06)
)
kmfunc(
  time = "sos_outtime_death",
  event = "sos_out_deathcv",
  eventname = "CVD",
  data = rsdata %>% filter(pop1),
  labposadj = c(-0.05, 0.09, 0.13)
)
kmfunc(
  time = "sos_outtime_hosphf",
  event = "sos_out_hosphf",
  eventname = "HFH",
  data = rsdata %>% filter(pop1),
  labposadj = c(-0.06, -0.06, -0.06)
)
mcffunc(
  event = "sos_out_hosphf",
  eventno = "sos_out_nohosphf",
  eventname = "HFH",
  data = rsdata %>% filter(pop1),
  datarec = rsdatarep %>% filter(pop1)
)
mcffunc(
  event = "sos_out_deathcvhosphf",
  eventno = "sos_out_deathcvnohosphf",
  eventname = "HFH/CVD",
  data = rsdata %>% filter(pop1),
  datarec = rsdatarep %>% filter(pop1)
)
kmfunc(
  time = "sos_outtime_death",
  event = "sos_out_death",
  eventname = "All-cause mortality",
  data = rsdata %>% filter(pop1),
  labposadj = c(-0.06, 0.12, 0.15)
)
```

```{r}
#| label: fig-cicmcf-pop-2
#| cache: true
#| cache.comments: false
#| dependson: kmfunc
#| fig-cap: "Cumulative incidence curve/Mean cumulative function - Population 2"
#| fig-subcap:
#|   - "HFH/CVD"
#|   - "CVD"
#|   - "HFH"
#|   - "Total HFH"
#|   - "Total HFH/CVD"
#|   - "All-cause mortality"
#| layout-ncol: 2
#| layout-nrow: 3

kmfunc(
  time = "sos_outtime_hosphf",
  event = "sos_out_deathcvhosphf",
  eventname = "HFH/CVD",
  data = rsdata,
  labposadj = c(-0.06, -0.06, -0.06)
)
kmfunc(
  time = "sos_outtime_death",
  event = "sos_out_deathcv",
  eventname = "CVD",
  data = rsdata,
  labposadj = c(-0.05, 0.08, 0.12)
)
kmfunc(
  time = "sos_outtime_hosphf",
  event = "sos_out_hosphf",
  eventname = "HFH",
  data = rsdata,
  labposadj = c(-0.06, -0.06, -0.06)
)
mcffunc(
  event = "sos_out_hosphf",
  eventno = "sos_out_nohosphf",
  eventname = "HFH",
  data = rsdata,
  datarec = rsdatarep
)
mcffunc(
  event = "sos_out_deathcvhosphf",
  eventno = "sos_out_deathcvnohosphf",
  eventname = "HFH/CVD",
  data = rsdata,
  datarec = rsdatarep
)
kmfunc(
  time = "sos_outtime_death",
  event = "sos_out_death",
  eventname = "All-cause mortality",
  data = rsdata,
  labposadj = c(-0.06, 0.12, 0.15)
)
```
