```{r}
#| label: outcomesfunc
#| cache: true
#| cache.comments: false

coxvars <- modvars
coxvars[modvars %in% stratavars] <- paste0("strata(", coxvars[modvars %in% stratavars], ")")

outcomesfunc <- function(data, impdata, time, event, eventname, xvar = "shf_loopdiuretic_cat", rep = FALSE, fg = FALSE) {
  levs <- levels(data %>% pull(!!sym(xvar)))
  nlevs <- length(levs)

  nrows <- if_else(fg, 4, 3)
  out <- data.frame(matrix(NA, ncol = 2 + nlevs + (nlevs - 1) * 3, nrow = nrows))
  colnames(out) <- c("Outcome", "Model", levs, paste0(c("hr", "lci", "uci"), rep(1:(nlevs - 1), each = 3)))

  out[, 1] <- eventname

  ## incidence rate
  out[1, 2] <- "No events, sum py, events/100py (95% CI)"

  # 1 row - incidence
  if (!rep) {
    ev <- data %>%
      group_by(!!sym(xvar)) %>%
      summarise(
        ev = sum(!!sym(event) == "Yes"),
        s = sum(!!sym(time) / 365.25),
        .groups = "drop"
      )
  }
  if (rep) {
    ev <- data %>%
      group_by(!!sym(xvar)) %>%
      summarise(
        ev = sum(!!sym(event)),
        s = sum(!!sym(time) / 365.25),
        .groups = "drop"
      )
  }

  r <- pois.exact(x = ev$ev, pt = ev$s / 100)

  out[1, 3:(nlevs + 2)] <- paste0(
    ev$ev, ", ",
    fn(ev$s, dig = 0), ", ",
    fn(r$rate, dig = 0), " (",
    fn(r$lower, dig = 0), "-",
    fn(r$upper, dig = 0), ")"
  )

  if (!rep) {
    ## 2 row - crude regression
    out[2, 2] <- "Crude HR (95% CI), p-value"
    mod <- summary(coxph(formula(paste0("Surv(", time, ",", event, "== 'Yes') ~ ", xvar)),
      data = data
    ))

    out[2, 3:(nlevs + 2)] <- c(
      "ref",
      paste0(
        fn(mod$conf.int[, "exp(coef)"], dig = 2),
        " (", fn(mod$conf.int[, "lower .95"], dig = 2),
        "-", fn(mod$conf.int[, "upper .95"], dig = 2), "), ",
        fn(mod$coef[, "Pr(>|z|)"], dig = 3, p = TRUE)
      )
    )

    ## 3 row - adjusted regression
    out[nrows, 2] <- "Adjusted HR (95% CI), p-value"
    mod <- summary(pool(with(impdata, coxph(formula(paste0(
      "Surv(", time, ",", event, " == 'Yes') ~ ", xvar, "+", paste(coxvars, collapse = " + ")
    ))))))

    out[nrows, 3:(nlevs + 2)] <- c(
      "ref",
      paste0(
        fn(exp(mod$estimate[1:(nlevs - 1)]), dig = 2),
        " (", fn(exp(mod$estimate[1:(nlevs - 1)] - global_z05 * mod$std.error[1:(nlevs - 1)]), dig = 2),
        "-", fn(exp(mod$estimate[1:(nlevs - 1)] + global_z05 * mod$std.error[1:(nlevs - 1)]), dig = 2), "), ",
        fn(mod$p.value[1:(nlevs - 1)], dig = 3, p = TRUE)
      )
    )

    out[nrows, paste0("hr", 1:(nlevs - 1))] <- exp(mod$estimate[1:(nlevs - 1)])
    out[nrows, paste0("lci", 1:(nlevs - 1))] <- exp(mod$estimate[1:(nlevs - 1)] - global_z05 * mod$std.error[1:(nlevs - 1)])
    out[nrows, paste0("uci", 1:(nlevs - 1))] <- exp(mod$estimate[1:(nlevs - 1)] + global_z05 * mod$std.error[1:(nlevs - 1)])

    if (fg) {
      out[3, 2] <- "Crude SHR (95% CI), p-value"
      mod <- summary(crr(
        ftime = data %>% pull(!!sym(time)),
        fstatus = data %>% pull(!!sym(paste0(event, "_cr"))),
        cov1 = data %>% select(starts_with(paste0(xvar, "_cr_"))),
        failcode = 1,
        cencode = 0
      ))

      out[3, 3:(nlevs + 2)] <- c(
        "ref",
        paste0(
          fn(mod$coef[, "exp(coef)"], dig = 2),
          " (",
          fn(exp(mod$coef[, "coef"] - global_z05 * mod$coef[, "se(coef)"]), dig = 2),
          "-",
          fn(exp(mod$coef[, "coef"] + global_z05 * mod$coef[, "se(coef)"]), dig = 2), "), ",
          fn(mod$coef[, "p-value"], dig = 3, p = TRUE)
        )
      )

      # out[5, 2] <- "Adjusted SHR (95% CI), p-value"
      # modvars_crr2 <- c(vars_crr[str_detect(vars_crr, paste0(xvar, "_cr_"))], modvars_crr)
      # mod <- crr_mids(time, paste0(event, "_cr"), xvars = modvars_crr2, impdata)
      # mod <- summary(pool(mod))
      #
      # out[5, 3:(nlevs + 2)] <- c(
      #   "ref",
      #   paste0(
      #     fn(exp(mod$estimate[1:(nlevs - 1)]), dig = 2),
      #     " (", fn(exp(mod$estimate[1:(nlevs - 1)] - global_z05 * mod$std.error[1:(nlevs - 1)]), dig = 2),
      #     "-", fn(exp(mod$estimate[1:(nlevs - 1)] + global_z05 * mod$std.error[1:(nlevs - 1)]), dig = 2), "), ",
      #     fn(mod$p.value[1:(nlevs - 1)], dig = 3, p = TRUE)
      #   )
      # )
    }
  }

  if (rep) {
    ## 2 row - crude regression
    out[2, 2] <- "Crude RR (95% CI), p-value"
    mod <- summary(glm.nb(formula(paste0(event, " ~ ", xvar, " + offset(log(sos_outtime_death))")),
      data = data %>% filter(sos_outtime_death > 0)
    ))

    out[2, 3:(nlevs + 2)] <- c("ref", paste0(
      fn(exp(mod$coefficients[2:nlevs, 1]), dig = 2),
      " (", fn(exp(mod$coefficients[2:nlevs, 1] - global_z05 * mod$coefficients[2:nlevs, 2]), dig = 2),
      "-", fn(exp(mod$coefficients[2:nlevs, 1] + global_z05 * mod$coefficients[2:nlevs, 2]), dig = 2), "), ",
      fn(mod$coefficients[2:nlevs, 4], dig = 3, p = TRUE)
    ))

    ## 3 row - adjusted regression
    impdata0 <- miceadds::subset_datlist(impdata, expr_subset = data %>% pull(sos_outtime_death) > 0)
    mod <- with(impdata0, glm.nb(formula(paste0(
      event, " ~ ", xvar, " + offset(log(sos_outtime_death)) + ",
      paste0(modvars, collapse = " + ")
    ))))
    mod <- summary(pool(mod))
    out[3, 2] <- "Adjusted RR (95% CI), p-value"
    out[3, 3:(nlevs + 2)] <- c("ref", paste0(
      fn(exp(mod$estimate[2:nlevs]), dig = 2),
      " (", fn(exp(mod$estimate[2:nlevs] - global_z05 * mod$std.error[2:nlevs]), dig = 2),
      "-", fn(exp(mod$estimate[2:nlevs] + global_z05 * mod$std.error[2:nlevs]), dig = 2), "), ",
      fn(mod$p.value[2:nlevs], dig = 3, p = TRUE)
    ))

    out[nrows, paste0("hr", 1:(nlevs - 1))] <- exp(mod$estimate[2:nlevs])
    out[nrows, paste0("lci", 1:(nlevs - 1))] <- exp(mod$estimate[2:nlevs] - global_z05 * mod$std.error[2:nlevs])
    out[nrows, paste0("uci", 1:(nlevs - 1))] <- exp(mod$estimate[2:nlevs] + global_z05 * mod$std.error[2:nlevs])
  }
  return(out)
}
```

```{r}
#| label: tbl-outcomes
#| cache: true
#| cache.comments: false
#| dependson: outcomesfunc
#| tbl-cap: "Association between loop diuretic and outcomes"

# Population 1

death <- outcomesfunc(
  data = rsdata %>% filter(pop1),
  impdata = imprsdata_pop1,
  time = "sos_outtime_death",
  event = "sos_out_death",
  eventname = "All-cause mortality"
)
cvdeath <- outcomesfunc(
  data = rsdata %>% filter(pop1),
  impdata = imprsdata_pop1,
  time = "sos_outtime_death",
  event = "sos_out_deathcv",
  eventname = "CVD",
  fg = T
)
hfhosp <- outcomesfunc(
  data = rsdata %>% filter(pop1),
  impdata = imprsdata_pop1,
  time = "sos_outtime_hosphf",
  event = "sos_out_hosphf",
  eventname = "First HFH",
  fg = T
)
rephfhosp <- outcomesfunc(
  data = rsdata %>% filter(pop1),
  impdata = imprsdata_pop1,
  time = "sos_outtime_death",
  event = "sos_out_nohosphf",
  eventname = "Total HFH",
  rep = TRUE
)
cvdeathhfhosp <- outcomesfunc(
  data = rsdata %>% filter(pop1),
  impdata = imprsdata_pop1,
  time = "sos_outtime_hosphf",
  event = "sos_out_deathcvhosphf",
  eventname = "CVD/First HFH",
  fg = T
)
cvdeathrephfhosp <- outcomesfunc(
  data = rsdata %>% filter(pop1),
  impdata = imprsdata_pop1,
  time = "sos_outtime_death",
  event = "sos_out_deathcvnohosphf",
  eventname = "CVD/Total HFH",
  rep = TRUE
)

outall_pop1 <- rbind(
  cvdeathhfhosp,
  cvdeath,
  hfhosp,
  rephfhosp,
  cvdeathrephfhosp,
  death
)

# Population 2

death <- outcomesfunc(
  data = rsdata,
  impdata = imprsdata,
  time = "sos_outtime_death",
  event = "sos_out_death",
  eventname = "All-cause mortality"
)
cvdeath <- outcomesfunc(
  data = rsdata,
  impdata = imprsdata,
  time = "sos_outtime_death",
  event = "sos_out_deathcv",
  eventname = "CVD",
  fg = T
)
hfhosp <- outcomesfunc(
  data = rsdata,
  impdata = imprsdata,
  time = "sos_outtime_hosphf",
  event = "sos_out_hosphf",
  eventname = "First HFH",
  fg = T
)
rephfhosp <- outcomesfunc(
  data = rsdata,
  impdata = imprsdata,
  time = "sos_outtime_death",
  event = "sos_out_nohosphf",
  eventname = "Total HFH",
  rep = TRUE
)
cvdeathhfhosp <- outcomesfunc(
  data = rsdata,
  impdata = imprsdata,
  time = "sos_outtime_hosphf",
  event = "sos_out_deathcvhosphf",
  eventname = "CVD/First HFH",
  fg = T
)
cvdeathrephfhosp <- outcomesfunc(
  data = rsdata,
  impdata = imprsdata,
  time = "sos_outtime_death",
  event = "sos_out_deathcvnohosphf",
  eventname = "CVD/Total HFH",
  rep = TRUE
)

outall_pop2 <- rbind(
  cvdeathhfhosp,
  cvdeath,
  hfhosp,
  rephfhosp,
  cvdeathrephfhosp,
  death
)

outall <- full_join(outall_pop1, outall_pop2, by = c("Outcome", "Model"))

outallprint <- outall %>%
  mutate(Outcome = if_else(Model == "No events, sum py, events/100py (95% CI)", Outcome, "")) %>%
  select(-starts_with("hr"), -starts_with("lci"), -starts_with("uci"))

cn <- colnames(outallprint)
cn <- str_remove_all(cn, "\\.x|\\.y")

make_one_xlsxsheet(outallprint, colnames = cn)

default_kable(outallprint,
  col.names = cn
) %>%
  add_header_above(c(" ", " ", "Population 1" = 3, "Population 2" = 3))
```
